*.docker.com
*.microsoft.com
*.amazonaws.com
telemetry.invicti.com
ctldl.windowsupdate.com
updates.acunetix.com
downloads.nessus.org
plugins.nessus.org
*.aws.amazon.com
*.fedoraproject.org
rhui3.us-east-1.aws.ce.redhat.com
*.download.windowsupdate.com
*.update.microsoft.com
*.windowsupdate.microsoft.com
*.slack.com
*.windows.com
*.duosecurity.com
*.okta.com
*.oktacdn.com
*.splunk.com
*.trendmicro.com
idp.login.splunk.com
manage.trendmicro.com
crl3.digicert.com
crl.godaddy.com
certificate.godaddy.com
ocsp.godaddy.com
crl4.digicert.com
*.digicert.com
*.rootca1.amazontrust.com
*.rootg2.amazontrust.com
*.amazontrust.com
*.sca1a.amazontrust.com
*.sca1b.amazontrust.com
powershellgallery.com